### ISSUE TITLE
Invalid character in group name, missing equal sign

### ISSUE THREAD

**Issue by rafi** [thinca/vim-guicolorscheme#1]
Error when running `GuiColorScheme hybrid` ([vim-hybrid](https://github.com/w0ng/vim-hybrid) colorscheme):

``` viml
Error detected while processing function <SNR>45_GuiColorScheme:
line   51:
W18: Invalid character in group name
E416: missing equal sign: link diffRemoved Constant
```

The line it fails on:

``` viml
hi! link diffRemoved Constant
```

**Comment by thinca** [comment]
Sorry.  Can not support it.
This plugin converts colorscheme file simply.  vim-hybrid is too complex to convert.  

vim-hybrid seems to be supporting GUI colorscheme.  You can use it directly.

Or, maybe you can use [CSApprox](https://github.com/godlygeek/csapprox).

**Comment by rafi** [comment]
Thanks for the quick answer.
